# Logistic Regression with Pytorch

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
# For reproducivility 
torch.manual_seed(1)

In [3]:
x_data =[[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data= [[0],[0],[0],[1],[1],[1]]

주어진 분류 문제를 생각해보자 : 학생들에 공부에 투자한 시간이 정보로 주어졌을때, 학생들의 시험 통과 여부를 예측하는 분류 문제. 강의를 한시간 듣고, 자습에 두시간 들었다면 x_data = [1,2] , 시험에 통과하지못했다면 y_data = [0]

In [4]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [5]:
print(x_train.shape)
print(y_train.shape)

torch.Size([6, 2])
torch.Size([6, 1])


### Learning parameters

In [6]:
# learning parameters
W = torch.zeros([2,1], requires_grad= True)
b = torch.zeros([1], requires_grad= True)

###  로지스틱 회귀모형 생성과 훈련 

In [7]:
optimizer = torch.optim.SGD([W,b], lr=0.05)

for epoch in range(nb_epochs) :     
    # 직접 이렇게 sigmoid를 구현해도 됌 
    # torch.sigmoid() 대신   직접 시그모이드 함수를 구현해도 됌 ->  1/(1+torch.exp(- x_train.matmul(W)+b))
    hypothesis = torch.sigmoid(x_train.matmul(W)+b)    
    cost = F.binary_cross_entropy(hypothesis, y_train)  # hypothesis, y_train 순서를 바꾸면 에러가 남 
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print(f'Epochs : {epoch+1}/{nb_epochs}   Cost : {cost}')

NameError: name 'nb_epochs' is not defined

In [78]:
# 훈련된 모델의 예측값
hypothesis

tensor([[0.0725],
        [0.1928],
        [0.4653],
        [0.7150],
        [0.8905],
        [0.9654]], grad_fn=<SigmoidBackward>)

In [79]:
# 실제 참값 
y_train

tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])

### pytorch가 제공하는 nn.Module을 사용하여 모델 구조화

In [80]:
class BinaryClassification(nn.Module) : 
    def __init__(self) : 
        super().__init__()
        self.logit = nn.Linear(2,1)
        
    def forward(self, x) : 
        logit = self.logit(x)
        return torch.sigmoid(logit)

In [81]:
model = BinaryClassification()

In [82]:
nb_epochs = 1000

optimizer = torch.optim.SGD(model.parameters(), lr=0.05)

for epoch in range(nb_epochs) : 
    hypothesis = model(x_train)
  
    cost = F.binary_cross_entropy(hypothesis, y_train)   # hypothesis, y_train 순서를 바꾸면 에러가 남 
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print(f'Epochs : {epoch+1}/{nb_epochs}   Cost : {cost}')
    

Epochs : 1/1000   Cost : 0.5397130846977234
Epochs : 2/1000   Cost : 0.5373921990394592
Epochs : 3/1000   Cost : 0.5353963971138
Epochs : 4/1000   Cost : 0.533607006072998
Epochs : 5/1000   Cost : 0.5319530963897705
Epochs : 6/1000   Cost : 0.5303915143013
Epochs : 7/1000   Cost : 0.5288956761360168
Epochs : 8/1000   Cost : 0.5274490714073181
Epochs : 9/1000   Cost : 0.5260414481163025
Epochs : 10/1000   Cost : 0.5246659517288208
Epochs : 11/1000   Cost : 0.5233184099197388
Epochs : 12/1000   Cost : 0.5219959616661072
Epochs : 13/1000   Cost : 0.5206964612007141
Epochs : 14/1000   Cost : 0.5194184184074402
Epochs : 15/1000   Cost : 0.5181609392166138
Epochs : 16/1000   Cost : 0.5169231295585632
Epochs : 17/1000   Cost : 0.5157042741775513
Epochs : 18/1000   Cost : 0.5145037174224854
Epochs : 19/1000   Cost : 0.513321042060852
Epochs : 20/1000   Cost : 0.5121555924415588
Epochs : 21/1000   Cost : 0.5110070705413818
Epochs : 22/1000   Cost : 0.5098749995231628
Epochs : 23/1000   Cost : 0

Epochs : 425/1000   Cost : 0.33936476707458496
Epochs : 426/1000   Cost : 0.33910536766052246
Epochs : 427/1000   Cost : 0.338846355676651
Epochs : 428/1000   Cost : 0.3385876715183258
Epochs : 429/1000   Cost : 0.3383293151855469
Epochs : 430/1000   Cost : 0.33807119727134705
Epochs : 431/1000   Cost : 0.33781352639198303
Epochs : 432/1000   Cost : 0.3375561237335205
Epochs : 433/1000   Cost : 0.33729907870292664
Epochs : 434/1000   Cost : 0.33704233169555664
Epochs : 435/1000   Cost : 0.3367859125137329
Epochs : 436/1000   Cost : 0.3365298807621002
Epochs : 437/1000   Cost : 0.336274117231369
Epochs : 438/1000   Cost : 0.3360186815261841
Epochs : 439/1000   Cost : 0.3357636034488678
Epochs : 440/1000   Cost : 0.335508793592453
Epochs : 441/1000   Cost : 0.33525434136390686
Epochs : 442/1000   Cost : 0.3350001573562622
Epochs : 443/1000   Cost : 0.3347463607788086
Epochs : 444/1000   Cost : 0.33449289202690125
Epochs : 445/1000   Cost : 0.3342397212982178
Epochs : 446/1000   Cost : 0.

Epochs : 874/1000   Cost : 0.24967147409915924
Epochs : 875/1000   Cost : 0.2495197057723999
Epochs : 876/1000   Cost : 0.24936817586421967
Epochs : 877/1000   Cost : 0.249216690659523
Epochs : 878/1000   Cost : 0.24906550347805023
Epochs : 879/1000   Cost : 0.248914435505867
Epochs : 880/1000   Cost : 0.24876350164413452
Epochs : 881/1000   Cost : 0.24861274659633636
Epochs : 882/1000   Cost : 0.24846218526363373
Epochs : 883/1000   Cost : 0.2483118176460266
Epochs : 884/1000   Cost : 0.24816156923770905
Epochs : 885/1000   Cost : 0.24801146984100342
Epochs : 886/1000   Cost : 0.2478615790605545
Epochs : 887/1000   Cost : 0.24771183729171753
Epochs : 888/1000   Cost : 0.24756227433681488
Epochs : 889/1000   Cost : 0.24741287529468536
Epochs : 890/1000   Cost : 0.24726366996765137
Epochs : 891/1000   Cost : 0.24711458384990692
Epochs : 892/1000   Cost : 0.24696564674377441
Epochs : 893/1000   Cost : 0.24681691825389862
Epochs : 894/1000   Cost : 0.24666832387447357
Epochs : 895/1000   

In [83]:
hypothesis

tensor([[0.0714],
        [0.1922],
        [0.4620],
        [0.7163],
        [0.8916],
        [0.9657]], grad_fn=<SigmoidBackward>)

In [70]:
y_train

tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])