# Pytorch Tensor Manipulation

### **강의자: DSL 5기 허유진**

First Author: Seungjae Ryan Lee (seungjaeryanlee at gmail dot com)
Second Author: Ki Hyun Kim (nlp.with.deep.learning at gmail dot com)

<div class="alert alert-warning">
    NOTE: This corresponds to <a href="https://www.youtube.com/watch?v=ZYX0FaqUeN4&t=23s&list=PLlMkM4tgfjnLSOjrEJN31gZATbcj_MpUm&index=25">Lab 8 of Deep Learning Zero to All Season 1 for TensorFlow</a>.
</div>

#### **Pytorch란?**

- 딥러닝 프레임워크
- 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼
- 개발자들과 연구자들이 쉽게 GPU를 활용하여 인공 신경망 모델을 만들고 학습시킬 수 있게 도와준다.


#### **Pytorch로 다루게 될 데이터의 형태**

- Vector: 1차원 데이터 배열

- Matrix: 2차원 데이터 배열

- 3D Tensor: 3차원 데이터 배열

#### **2차원 matrix의 크기 계산**
batch size * dimension


#### **3차원 tensor의 크기 계산 (Computer Vision)**
batch size * width * height


#### **3차원 tensor의 크기 계산 (시계열 데이터, Natural Language Processing)**
batch size * length * dimension

(이때 dimension * length는 한 문장을 의미한다.)



## Imports

In [1]:
!pip install -r requirements.txt

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
You should consider upgrading via the 'c:\anaconda\python.exe -m pip install --upgrade pip' command.


Run `pip install -r requirements.txt` in terminal to install all required Python packages.

In [2]:
import numpy as np
import torch

ModuleNotFoundError: No module named 'torch'

## NumPy Review

We hope that you are familiar with `numpy` and basic linear algebra.

Pytorch 자체는 numpy와 굉장히 유사하다. 또는 더 나은 기능을 제공한다.

### 1D Array with NumPy

In [2]:
# 1D array 선언
# list에 넣고 np.array 함수에 넣기

t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank  of t: ', t.ndim) # t의 차원이 궁금하다 -> 1차원 벡터
print('Shape of t: ', t.shape) # t의 shape이 궁금하다 -> 하나의 차원에 대해 7개의 element가 들어있다

Rank  of t:  1
Shape of t:  (7,)


In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Element
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1])   # Slicing
print('t[:2] t[3:]     = ', t[:2], t[3:])      # Slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


### 2D Array with NumPy

In [5]:
# 2D array 선언

t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [6]:
print('Rank  of t: ', t.ndim) # t의 차원이 궁금하다 -> 2차원 행렬
print('Shape of t: ', t.shape) # t의 shape이 궁금하다 -> 두 개의 차원에 각각 4개, 3개의 element가 들어있다. 4 X 3 matrix인 것.

Rank  of t:  2
Shape of t:  (4, 3)


## PyTorch is like NumPy (but better)

### 1D Array with PyTorch

In [7]:
# Pytorch에서의 1D array 선언
# Python list로 값을 넣어준 후에, torch.FloatTensor 함수 이용
# torch에 float 형태로 값을 넣어줘라.

t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [8]:
print(t.dim())  # rank  # 차원의 개수: 1개
print(t.shape)  # shape # 모양은: 7개의 element가 있다
print(t.size()) # shape # 위와 같은 값
print(t[0], t[1], t[-1])  # Element
print(t[2:5], t[4:-1])    # Slicing
print(t[:2], t[3:])       # Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2D Array with PyTorch

In [9]:
# Pytorch에서의 2D array 선언
# Python list로 값을 넣어준 후에, torch.FloatTensor 함수 이용
# torch에 float 형태로 값을 넣어줘라.

t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t) # 4 X 3 matrix

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
print(t.dim())  # rank  # 차원: 2차원
print(t.size()) # shape # 각 차원에 4개, 3개의 element가 있다
print(t[:, 1])
print(t[:, 1].size())   # 4개의 element를 가진 vector이다.
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Broadcasting

<div class="alert alert-warning">
    Carelessly using broadcasting can lead to code hard to debug.
</div>

Pytorch에서는 broadcasting이라는 기능을 제공한다.

matrix 연산법칙
- 합/차 연산에서는 두 행렬의 크기가 같아야 한다.
- 행렬곱 연산에서는 첫 행렬의 마지막 차원과 두 번째 행렬의 첫 번째 차원이 일치해야 한다.

but! 불가피하게 다른 크기의 행렬을 더하거나 빼는 사칙연산을 수행해야하는 상황이 발생할 수 있다.

이때 pytorch에서 제공하는 broadcasting 기능을 통해 자동적으로 size를 맞추어 연산을 수행할 수 있다.

In [11]:
# Same shape
# 같은 크기. 1X2로 size가 같다. 쉽게 더할 수 있다.

m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [12]:
# Vector + scalar
# 원래는 연산을 수행할 수 없지만, pytorch가 자동으로 같은 size의 matrix 또는 tensor로 변환하여 연산을 수행할 수 있도록 해준다.

m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

tensor([[4., 5.]])


In [13]:
# 2 x 1 Vector + 1 x 2 Vector
# 두 벡터의 크기를 2 x 2로 바꾸어 연산한다. (차원을 늘려주는 것)
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


broadcasting은 편리하지만, 자동으로 실행되는 기능이므로 사용자 입장에서 굉장히 주의해서 사용해야 한다.

실수를 해도 오류가 나지 않기 때문에 어디에서 틀렸는지 찾기가 어렵다!

## Frequently Used Operations in PyTorch

### Multiplication vs Matrix Multiplication

딥러닝은 행렬곱 연산을 아주 많이 사용하는 알고리즘이다.

따라서 행렬곱을 이해하고 구현하는 것이 매우 중요!

일반적인 곱셈: 두 matrix의 size가 같아야한다.



In [14]:
print()
print('-------------')
print('Multiplication vs Matrix Multiplication')
print('-------------')

# 행렬곱 
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1


# 일반적인 곱셈
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1  # 이것이 2 x 2로 broadcasting되어 계산됨
print(m1 * m2) # 2 x 2
print(m1.mul(m2))


-------------
Multiplication vs Matrix Multiplication
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Mean

In [15]:
t = torch.FloatTensor([1, 2]) # [1,2]값을 가진 float tensor를 선언한다.
print(t.mean()) # mean을 구해라.

tensor(1.5000)


In [16]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [17]:
print(t.mean())         # 전체 4개 element에 대한 mean
print(t.mean(dim=0))    # numpy의 axis가 torch의 dim을 의미. 열 끼리의 mean을 구한 것
print(t.mean(dim=1))    # 행 끼리의 mean을 구한 것
print(t.mean(dim=-1))   # 행 끼리의 mean을 구한 것

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### Sum

In [18]:
t = torch.FloatTensor([[1, 2], [3, 4]])  # 2 x 2의 행렬을 선언
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [19]:
print(t.sum())
print(t.sum(dim=0))    # 열의 sum을 구한 것
print(t.sum(dim=1))    # 행의 sum을 구한 것
print(t.sum(dim=-1))   # 행의 sum을 구한 것

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max and Argmax

In [20]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


The `max` operator returns one value if it is called without an argument.

In [21]:
print(t.max()) # max: 가장 큰 값을 반환한다.

tensor(4.)


The `max` operator returns 2 values when called with dimension specified. The first value is the maximum value, and the second value is the argmax: the index of the element with maximum value.

In [22]:
print(t.max(dim=0)) # Returns two values: max and argmax
# 각 열에서 가장 큰 value 반환, 각 열에서 가장 큰 값의 index를 반환

print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])  # argmax: 가장 큰 값의 index를 반환한다.

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [23]:
# 각 행에서 가장 큰 value 반환, 각 행에서 가장 큰 값의 index를 반환
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### View

<div class="alert alert-warning">
    This is a function hard to master, but is very useful!
</div>

numpy의 reshape와 같은 역할을 한다.

shape을 다시 만드는 것.

In [24]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

# 2 x 2 x 3 의 tensor 선언

torch.Size([2, 2, 3])


In [25]:
print(ft.view([-1, 3]))        # -1의 의미: 정해주지 않았다.  #두 번째 차원에서는 3개의 element를 가진다.
                               # 자동적으로 4 x 3의 행렬이 나온다.
print(ft.view([-1, 3]).shape)

# view 함수를 통해 2 x 2 x 3 tensor를 4 x 3으로 바꾸었다.

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [26]:
print(ft.view([-1, 1, 3]))        # 괄호 안의 숫자들의 곱이 기존 tensor의 크기와 같기만 하면 된다.
                                  # 자동적으로 4 x 1 x 3의 행렬이 나온다.
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze

쥐어 짜다. dimension이 1인 경우 그 dimension을 없애준다.

In [27]:
ft = torch.FloatTensor([[0], [1], [2]])    # 3 x 1 의 vector에서 열을 없애줌. 즉, 0,1,2의 원소를 가진 1차원 벡터로 만들어버린다.
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [28]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [29]:
print(ft.squeeze(dim=0)) # 설정해준 dimension이 1차원이라면 그 차원을 없애라.
# 여기에서 첫번째 차원은 1차원이 아니므로 변형되지 않고 그대로 나온다.

tensor([[0.],
        [1.],
        [2.]])


### Unsqueeze

내가 원하는 dimension에 1을 넣어준다. dimension을 반드시 명시해주어야한다.

In [30]:
ft = torch.Tensor([0, 1, 2])  # 1차원 벡터를 선언
print(ft.shape)

torch.Size([3])


In [31]:
print(ft.unsqueeze(0))  # dim=0 즉 첫 번째 dimension에 1을 넣어라
print(ft.unsqueeze(0).shape)  # 1 x 3의 크기가 된다.

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [32]:
print(ft.view(1, -1))   # 뒷부분은 모르겠고(-1), 처음에 1을 넣어라.
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [34]:
print(ft.unsqueeze(1))     # dim=1 즉 두 번째 dimension에 1을 넣어라
print(ft.unsqueeze(1).shape)   # 3 x 1의 크기가 된다.

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [35]:
print(ft.unsqueeze(-1))       # 마지막 dimension 즉 두 번째 dimension에 1을 넣어라
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Casting

tensor의 type을 바꾸어주겠다.

In [36]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [37]:
print(lt.float())   # long type으로 선언한 tensor를 float type으로 바꿔줘라

tensor([1., 2., 3., 4.])


In [38]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [39]:
print(bt.long())    # boolean type으로 선언한 tensor를 long type으로 바꿔줘라.
print(bt.float())   # boolean typedmfh 선언한 tensor를 float type으로 바꿔줘라.

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenation

이어붙인다.

In [40]:
x = torch.FloatTensor([[1, 2], [3, 4]])   # 2 x 2
y = torch.FloatTensor([[5, 6], [7, 8]])   # 2 x 2

In [41]:
print(torch.cat([x, y], dim=0))   # dim=0 즉, 첫 번째 dimension이 늘어나도록 위아래로 붙여라.
print(torch.cat([x, y], dim=1))   # dim=1 즉, 두 번째 dimension이 늘어나도록 양옆으로 붙여라.

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking

concatenation 작업을 편리하게 해준다.

In [44]:
# x,y,z 모두 1 x 2 vector

x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [45]:
# stack() 안에 list 형태로 tensor들이 들어가있다.

print(torch.stack([x, y, z]))         # 위아래 방향으로 쌓아라
print(torch.stack([x, y, z], dim=1))  # 양옆으로 쌓아라

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [47]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

# 위 결과는, x,y,z를 unsqueeze하여 concat한 결과와 같다.

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Ones and Zeros Like

In [48]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [50]:
print(torch.ones_like(x))   # 1로만 가득한, 똑같은 size의 tensor가 출력된다.
print(torch.zeros_like(x))  # 0으로 가득한, 똑같은 size의 tensor가 출력된다.

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation

In [51]:
x = torch.FloatTensor([[1, 2], [3, 4]])
x

tensor([[1., 2.],
        [3., 4.]])

In [52]:
print(x.2mul(.))  # x의 각 원소에 곱하기 2를 해라.
print(x)
print(x.mul_(2.)) # In-place opertation을 하려면 underbar(_)를 이용.
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
